name: Cypress Tests
on: [push]
jobs: 
  ui-tests:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: Cypress.io
        uses: cypress-io/github-action@v5.6.1
        with:
          browser: chrome
        
