name: Cypress Tests
on: [push]
jobs: 
  ui-tests:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: Cypress.io
        uses: cypress-io/github-action@v5.6.1
        with:
          browser: chrome
          command: npm run ui-regression
      - name: Uploading artifacts
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-execution-report
          path: cypress/reports/html
          retention-days: 30
